In [15]:
import numpy as np

In [8]:
arr1 = np.array([1,2,3,4,5])

In [9]:
arr1.shape

(5,)

In [21]:
arr2 = np.array([[1,2,3,4,5]])

In [22]:
arr2.shape

(1, 5)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr1.ndim

1

In [25]:
arr2.ndim

2

In [16]:
arr1 = np.array([1,2,3,4,5], dtype = np.float)

C:\Users\79189\AppData\Local\Temp/ipykernel_12640/3555131695.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1 = np.array([1,2,3,4,5], dtype = np.float)


In [17]:
arr1.dtype

dtype('float64')

In [28]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr2 = np.arange(0, 10, 1.5)
arr2

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [30]:
arr_random = np.random.random((10,))

In [31]:
arr_random

array([0.42307785, 0.67021227, 0.04952819, 0.24329744, 0.75454349,
       0.60027415, 0.74060609, 0.58584171, 0.54972635, 0.45088406])

In [32]:
arr2

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [35]:
arr2_sqrt = np.sqrt(arr2)
arr2_sqrt

array([0.        , 1.22474487, 1.73205081, 2.12132034, 2.44948974,
       2.73861279, 3.        ])

In [42]:
arr1 = np.arange(10,17)

In [43]:
arr1

array([10, 11, 12, 13, 14, 15, 16])

In [44]:
arr1 + arr2

array([10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ])

In [45]:
arr1 * arr2

array([  0. ,  16.5,  36. ,  58.5,  84. , 112.5, 144. ])

In [46]:
arr1**2

array([100, 121, 144, 169, 196, 225, 256], dtype=int32)

In [47]:
arr1

array([10, 11, 12, 13, 14, 15, 16])

In [48]:
arr1.sum()

91

In [49]:
arr1.std()

2.0

In [50]:
arr1.max()

16

In [52]:
arr1.mean()

13.0

In [53]:
arr1 > 14

array([False, False, False, False, False,  True,  True])

In [59]:
arr54 = np.arange(5,20)
arr54

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [60]:
arr54.ndim

1

In [61]:
arr54.shape

(15,)

In [63]:
arr54.std()

4.320493798938574

In [64]:
arr1

array([10, 11, 12, 13, 14, 15, 16])

In [77]:
np.insert(arr1, 5, 10)

array([10, 11, 12, 13, 14, 10, 15, 16])

In [78]:
np.delete(arr1, 5)

array([10, 11, 12, 13, 14, 16])

In [79]:
arr3 = np.array([1,10,5,33,3])
np.sort(arr3)

array([ 1,  3,  5, 10, 33])

In [80]:
arr1

array([10, 11, 12, 13, 14, 15, 16])

In [81]:
arr2

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [83]:
arr = np.concatenate((arr1,arr2))
arr

array([10. , 11. , 12. , 13. , 14. , 15. , 16. ,  0. ,  1.5,  3. ,  4.5,
        6. ,  7.5,  9. ])

In [85]:
arr[(arr < 5)]

array([0. , 1.5, 3. , 4.5])

In [86]:
arr[(arr < 10) & (arr > 5)]

array([6. , 7.5, 9. ])

In [89]:
arr[(arr < 3) | (arr > 17)]

array([0. , 1.5])

In [94]:
matrix1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
matrix1.shape

(3, 3)

In [96]:
matrix1.size

9

In [97]:
matrix1.ndim

2

In [102]:
matrix1.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [101]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [107]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [108]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [112]:
np.empty(2)

array([0. , 1.5])

In [113]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
matrix2 = np.array([(10,11,12),(13,14,15),(16,17,18)])

In [119]:
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [120]:
matrix1 + matrix2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [121]:
np.delete(matrix1,2,axis=0) #axis = 0  row,axis = 1  column

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
np.mean(matrix1, axis=0)

array([4., 5., 6.])

In [125]:
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [126]:
matrix2[1,2]

15

In [127]:
matrix2[:,1]

array([11, 14, 17])

In [128]:
matrixlove = np.array([(1,3,5,7),(2,4,6,8),(9,11,13,15)])

In [129]:
matrixlove

array([[ 1,  3,  5,  7],
       [ 2,  4,  6,  8],
       [ 9, 11, 13, 15]])

In [130]:
matrixlike = np.array([(16,18,20,22),(17,19,21,23),(24,26,28,30)])

In [131]:
matrixlike

array([[16, 18, 20, 22],
       [17, 19, 21, 23],
       [24, 26, 28, 30]])

In [132]:
new_matrix = np.append(matrixlove,10)

In [133]:
new_matrix

array([ 1,  3,  5,  7,  2,  4,  6,  8,  9, 11, 13, 15, 10])

In [135]:
matrixlove[matrixlike > 5]

array([ 1,  3,  5,  7,  2,  4,  6,  8,  9, 11, 13, 15])

In [136]:
np.delete(matrixlove,2,axis=1) #axis = 1 row, axis = 2 column

array([[ 1,  3,  7],
       [ 2,  4,  8],
       [ 9, 11, 15]])