In [3]:
import numpy as np


In [4]:
matrix1 = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
matrix1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
matrix2 = np.array([(1,3,5),(2,4,6),(7,9,11),(8,10,12)])
matrix2

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [ 7,  9, 11],
       [ 8, 10, 12]])

In [6]:
matrix1 + matrix2

array([[ 2,  5,  8],
       [ 6,  9, 12],
       [14, 17, 20],
       [18, 21, 24]])

In [7]:
matrix1[1,2]

6

In [8]:
matrix1[:,1]

array([ 2,  5,  8, 11])

In [9]:
matrix1[2,2]

9

In [10]:
matrix1[matrix1 > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [11]:
matrix1[matrix1 < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
matrix2[matrix2 > 5]

array([ 6,  7,  9, 11,  8, 10, 12])